
# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/riyakadakia/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/riyakadakia/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/riyakadakia/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/riyakadakia/Downloads/google-cloud-sdk/completion.bash.inc'; fi

export API_KEY="pk_93f4bdb8cb9e46d2a273b5c077df8db0"
export FLASK_APP="application.py"
